### ISSUE TITLE
Error compiling for Teensy 3.2 in Arduino 1.6.133

### ISSUE THREAD

**Issue by mswartz** [sparkfun/Proto_Pedal#4]
Hi, thanks for a fun tutorial! Got the hardware running, am trying to use some of the software examples. Throughput works fine, but I'm running into this problem with the echo sketch:

```echo: In function 'void loop()':
echo:178: warning: unused variable 'next_on' 
   static bool next_on = true;
               ^
/Applications/Arduino.app/Contents/Java/hardware/tools/arm/bin/../lib/gcc/arm-none-eabi/4.8.4/../../../../arm-none-eabi/bin/ld: /var/folders/t2/8mc1sfxx51d39b6_826qt5c00000gn/T/arduino_build_49085/echo.ino.elf section `.bss' will not fit in region `RAM'
/Applications/Arduino.app/Contents/Java/hardware/tools/arm/bin/../lib/gcc/arm-none-eabi/4.8.4/../../../../arm-none-eabi/bin/ld: region `RAM' overflowed by 1280 bytes
collect2: error: ld returned 1 exit status
Multiple libraries were found for "SD.h"
 Used: /Applications/Arduino.app/Contents/Java/hardware/teensy/avr/libraries/SD
 Not used: /Applications/Arduino.app/Contents/Java/libraries/SD
Error compiling for board Teensy 3.2 / 3.1.```

Any ideas for how to fix this?

**Comment by Jacquot-SFE** [comment]
I've seen this before.  Two things to try.

First, make sure you've got a non-optimized target selected in the "tools->cpu speed" menu.  The optimized builds supposedly run faster, but use more RAM.  You don't need the computational cycles, but more RAM means longer max delay time, which you probably _do_ want.

Second, if that fails (the internals may have changed since I wrote the sketch), take the number in the error message (ie: the 1280 bytes), and subtract it from the LEN constant.

**Comment by mswartz** [comment]
Ah, thanks! I reduced LEN to `0x06300` and it worked, albeit with a low memory warning. Thanks for the quick help.

**Comment by mswartz** [comment]
Also just confirmed that changing the CPU speed works as well. Great tips, thanks!
